---
language: python
services: docker

env:
  global:
    - ROLE_NAME: knxd

matrix:
  include:
    - env:
        - MOLECULE_DISTRO: debian9
        - SCENARIO: default
    - env:
        - MOLECULE_DISTRO: debian10
        - SCENARIO: default
    - env:
        - MOLECULE_DISTRO: debian10
        - SCENARIO: deb_repo
    - env:
        - MOLECULE_DISTRO: debian11
        - SCENARIO: default
    - env:
        - MOLECULE_DISTRO: debian11
        - SCENARIO: deb_repo

install:
  # Install test dependencies, newer molecule version do not depend on ansible
  # must be installed separately
  # - apt-get -y install ansible
  - pip install molecule[lint,docker,ansible] docker pytest-testinfra ansible-lint

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME sseide.$ROLE_NAME
  - cd sseide.$ROLE_NAME
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_LOGIN" --password-stdin

script:
  # Run tests.
  - molecule test --scenario-name $SCENARIO

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
