---
# task to install knxd from existing debian repository
- name: "set_fact: Create list of knxd packages for installation"
  set_fact:
    knxd_deb_list: ['knxd', 'knxd-tools', 'knxd-dev']

- name: "Check if dev package shall be installed too"
  set_fact:
    knxd_deb_list: "{{ knxd_deb_list | reject('regex', 'knxd-dev.*') | list }}"
  when: not knxd_install_dev_package

- name: "Install knxd packages from repo"
  apt:
    name: "{{ knxd_deb_list }}"
    state: present
  notify: Restart knxd
