---
- include: source.yml
  when: knxd_source_compile

- include: deb_repo.yml
  when: not knxd_source_compile

- debug:
    var: knxd_arg_connection

- name: "Install ini file"
  template:
    src: "{{ knxd_config_file }}"
    dest: "/etc/knxd.ini"
  notify: Restart knxd

- include: knxd_systemd.yml
  when: ansible_service_mgr == "systemd"

- include: knxd_non_systemd.yml
  when: ansible_service_mgr != "systemd"

- name: "Configure monit"
  template:
    src: "templates/knxd.monit"
    dest: "/etc/monit/conf.d/knxd"
  when: knxd_use_monit
  notify: Reload monit
