---
- include: source.yml
  when: knxd_source_compile

- include: deb_repo.yml
  when: not knxd_source_compile

- debug:
    var: knxd_arg_connection

- name: "Install ini file"
  template:
    src: "{{knxd_config_file}}"
    dest: "/etc/knxd.ini"
  notify: Restart knxd

- name: "Configure systemd to pick up ini file"
  lineinfile:
    path: "/etc/knxd.conf"
    line: "KNXD_OPTS=/etc/knxd.ini"
    regexp: "^KNXD_OPTS=.*$"
    state: present
    create: true
  register: knxd_systemd changed
  notify: Restart knxd

- name: "Configure monit"
  template:
    src: "templates/knxd.monit"
    dest: "/etc/monit/conf.d/knxd"
  notify: Reload monit
  when: knxd_use_monit
