---
# this role checks installation via debian repository.
# this works only at debian buster and newer as default, older releases do not have
# a precompiled knxd package available.

- name: Converge
  hosts: all
  pre_tasks:
    # needed as long as debian version is below 10/buster as knxd is pre-packages on 10+ only
    # add testing sources to apt and make it less preferred
    - name: 'PRE: add buster apt sources on debian 9'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '<'))
      lineinfile:
        path: '/etc/apt/sources.list.d/buster.list'
        line: 'deb http://ftp.de.debian.org/debian buster main'
        state: present
        create: true

    - name: 'PRE: set buster preferences for apt on debian 9'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '<'))
      blockinfile:
        path: '/etc/apt/preferences.d/buster.pref'
        state: present
        create: true
        block: |
          Package: *
          Pin: release a=testing
          Pin-Priority: 200

    - name: 'PRE: add buster backports apt sources on debian 10 (monit)'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '='))
      lineinfile:
        path: '/etc/apt/sources.list.d/backports.list'
        line: 'deb http://ftp.gwdg.de/pub/linux/debian/debian/ buster-backports main'
        state: present
        create: true

    - name: 'PRE: set backport preferences for apt on debian 10'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '='))
      blockinfile:
        path: '/etc/apt/preferences.d/backports.pref'
        state: present
        create: true
        block: |
          Package: *
          Pin: release a=buster-backports
          Pin-Priority: 450

    - name: Update apt cache.
      apt:
        name: python-apt
        state: present
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # needed to test use_monit feature
    - name: 'PRE: install monit for role test'
      apt:
        name: monit
        state: present

  roles:
    - role: sseide.knxd
      knxd_source_compile: false
      knxd_use_monit: true
      knxd_arg_drivers:
        - driver: "dummy"
        - driver: "ip"
