---
# this role checks installation via debian repository.
# this works only at debian buster and newer as default, older releases do not have
# a precompiled knxd package available.

- name: Converge
  hosts: all
  pre_tasks:
    # knxd is only part of debian version is 10+ as existing package
    # do not allow running this one against older debian versions
    - name: 'PRE: exit with failure if debian version is older than 10'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '<'))
      ansible.builtin.fail:
        msg: 'Cannot run this playbook on Debian before Buster (10)'

    - name: 'PRE: add buster backports apt sources on debian 10 (monit)'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '='))
      lineinfile:
        path: '/etc/apt/sources.list.d/backports.list'
        line: 'deb http://ftp.gwdg.de/pub/linux/debian/debian/ buster-backports main'
        state: present
        create: true

    - name: 'PRE: set backport preferences for apt on debian 10'
      when: ansible_distribution == 'Debian' and (ansible_distribution_version is version('10', '='))
      blockinfile:
        path: '/etc/apt/preferences.d/backports.pref'
        state: present
        create: true
        block: |
          Package: *
          Pin: release a=buster-backports
          Pin-Priority: 450

    - name: 'PRE: Update apt cache and install python-apt'
      apt:
        name: python-apt
        state: present
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # needed to test use_monit feature
    - name: 'PRE: install monit for role test'
      apt:
        name: monit
        state: present

  roles:
    - role: sseide.knxd
      knxd_source_compile: false
      knxd_use_monit: true
      knxd_arg_drivers:
        - driver: "dummy"
        - driver: "ip"
          filters:
            - single
            - retry
        - driver: "tpuart"
          filters: "single"
        - driver: "tpuart"
          baudrate: "56000"
