---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 molecule/

platforms:
  - name: instance
    # need at least debian 10 Buster to test installation of knxd from repo
    # workaround for debian 9: add buster repo to apt sources...
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # ansible flags recompile of source as changed, idempotence only working if recompile not forced
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
