---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: sseide.knxd
      knxd_source_compile: true
      knxd_arg_driver: ""
      # knxd_skip_package_build: true
      knxd_arg_drivers:
        - driver: "dummy"
        - driver: "ip"
